title: Sergio's Website
description: random dogs generator I guess
theme: just-the-docs

url: https://checochocks.github.io/website/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
